services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: takobox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./takobox_data:/data:ro
    ports:
      - 80:80
    extra_hosts:
      - "web backend:host-gateway"
    environment:
      - BASE_URL=":80"

volumes:
  postgres_data:
