services:
  web:
    image: takobox-web:dev
    environment:
      - TAKOBOX_INTERNAL_API_URL=http://backend:8000
      - TAKOBOX_DISABLE_LANDING_PAGE=true
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: takobox-server:dev
    environment:
      - TAKOBOX_DATABASE_URL="postgres://postgres:password@db:5432/takobox"
      - TAKOBOX_SESSION_SECRET="<super_secret_session_secret_please_change_pretty_please_i_beg_you>"
      - TAKOBOX_DATA_DIR="/takobox_data"
    volumes:
      - ./takobox_data:/takobox_data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: takobox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./takobox_data/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    environment:
      - BASE_URL=":80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./takobox_data:/data:ro
    ports:
      - 80:80
    restart: unless-stopped
