services:
  takobox:
    image: ghcr.io/myuwi/takobox:main
    environment:
      - TAKOBOX_SESSION_SECRET=super-secret-session-secret-please-change-pretty-please-i-beg-you
      - TAKOBOX_ENABLE_ACCOUNT_CREATION=false
      - TAKOBOX_DISABLE_LANDING_PAGE=true
    volumes:
      - ./takobox_data:/takobox_data
    ports:
      - 8080:80
    restart: unless-stopped
