services:
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./takobox_data:/takobox_data:ro
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TAKOBOX_SERVER_UPSTREAM=host.docker.internal:8000
      - TAKOBOX_WEB_UPSTREAM=host.docker.internal:3000
