name = "takobox"
version = "0.0.1"

[dependencies]
antigone = ">= 1.1.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
given = ">= 5.0.4 and < 6.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_erlang = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_stdlib = ">= 0.61.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
mist = ">= 5.0.1 and < 6.0.0"
pog = ">= 4.0.0 and < 5.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
youid = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
squirrel = ">= 4.0.0 and < 5.0.0"
