list:
  @just --list

dev-deps:
  cargo install watchexec-cli sqlx-cli

dev:
  watchexec -r -w Cargo.toml -w src 'cargo run'

test:
  DATABASE_URL=$TAKOBOX_DATABASE_URL cargo test

prepare:
  cargo sqlx prepare --database-url $TAKOBOX_DATABASE_URL
