list:
  @just --list

dev:
  watchexec --restart --clear --wrap-process=session --watch . --ignore build -- "gleam run"

test:
  dbmate -e TEST_DATABASE_URL up
  gleam test

migrate:
  dbmate up
  gleam run -m squirrel
