/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in to a user account
         */
        post: operations["takobox.routes.auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out of a user account, invalidating the login session
         */
        post: operations["takobox.routes.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a user account
         */
        post: operations["takobox.routes.auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get collections
         * @description Get the current user's collections
         */
        get: operations["takobox.routes.collections.index"];
        put?: never;
        /**
         * Create collection
         * @description Create a collection
         */
        post: operations["takobox.routes.collections.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete collection
         * @description Delete a collection belonging to the current user
         */
        delete: operations["takobox.routes.collections.delete"];
        options?: never;
        head?: never;
        /**
         * Rename collection
         * @description Rename a collection belonging to the current user
         */
        patch: operations["takobox.routes.collections.rename"];
        trace?: never;
    };
    "/api/collections/{collection_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get files
         * @description Get the files belonging to the current user
         */
        get: operations["takobox.routes.collection_files.index"];
        put?: never;
        /**
         * Add file to collection
         * @description Add a file to a collection belonging to the current user
         */
        post: operations["takobox.routes.collection_files.add"];
        /**
         * Remove file from collection
         * @description Remove a file from a collection belonging to the current user
         */
        delete: operations["takobox.routes.collection_files.remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get files
         * @description Get the files belonging to the current user
         */
        get: operations["takobox.routes.files.index"];
        put?: never;
        /**
         * Upload file
         * @description Upload a file
         */
        post: operations["takobox.routes.files.upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file
         * @description Get a file belonging to the current user
         */
        get: operations["takobox.routes.files.show"];
        put?: never;
        post?: never;
        /**
         * Delete file
         * @description Delete a file belonging to the current user
         */
        delete: operations["takobox.routes.files.delete"];
        options?: never;
        head?: never;
        /**
         * Rename file
         * @description Rename a file belonging to the current user
         */
        patch: operations["takobox.routes.files.rename"];
        trace?: never;
    };
    "/api/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download file
         * @description Download a file belonging to the current user
         */
        get: operations["takobox.routes.files.download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_id}/regenerate-thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate thumbnail
         * @description Regenerate the thumbnail for a file belonging to the current user
         */
        post: operations["takobox.routes.files.regenerate_thumbnail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get information about the currently logged in user
         */
        get: operations["takobox.routes.me.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get settings
         * @description Get settings for the Takobox instance
         */
        get: operations["takobox.routes.settings.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "salvo_core.http.errors.status_error.StatusError": {
            brief: string;
            cause?: string;
            /** Format: uint16 */
            code: number;
            detail: string;
            name: string;
        };
        "takobox.error.ErrorResponse": {
            message: string;
        };
        "takobox.models.collection.Collection": {
            createdAt: string;
            id: components["schemas"]["takobox.types.uid.Uid"];
            name: string;
        };
        "takobox.models.collection.FileCollection": {
            id: components["schemas"]["takobox.types.uid.Uid"];
            name: string;
        };
        "takobox.models.file.File": {
            createdAt: string;
            filename: string;
            id: components["schemas"]["takobox.types.uid.Uid"];
            name: string;
            /** Format: int64 */
            size: number;
        };
        "takobox.models.file.FileWithCollections": components["schemas"]["takobox.models.file.File"] & {
            collections: components["schemas"]["takobox.models.collection.FileCollection"][];
        };
        "takobox.models.settings.Settings": {
            enableAccountCreation: boolean;
            maxFileSize: number;
        };
        "takobox.models.user.User": {
            createdAt: string;
            id: components["schemas"]["takobox.types.uid.Uid"];
            username: string;
        };
        "takobox.routes.auth.AuthPayload": {
            password: string;
            username: string;
        };
        "takobox.routes.collection_files.CollectionFilesPayload": {
            id: components["schemas"]["takobox.types.uid.Uid"];
        };
        "takobox.routes.collections.CreateCollectionPayload": {
            name: string;
        };
        "takobox.routes.collections.RenameCollectionPayload": {
            name: string;
        };
        "takobox.routes.files.RenameFilePayload": {
            name: string;
        };
        "takobox.types.uid.Uid": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "takobox.routes.auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.auth.AuthPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.auth.AuthPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collections.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.collection.Collection"][];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collections.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.collections.CreateCollectionPayload"];
            };
        };
        responses: {
            /** @description Response with json format data */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.collection.Collection"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collections.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `collection_id` from request url path. */
                collection_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collections.rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `collection_id` from request url path. */
                collection_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.collections.RenameCollectionPayload"];
            };
        };
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.collection.Collection"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collection_files.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `collection_id` from request url path. */
                collection_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.file.File"][];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collection_files.add": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `collection_id` from request url path. */
                collection_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.collection_files.CollectionFilesPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.collection_files.remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `collection_id` from request url path. */
                collection_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.collection_files.CollectionFilesPayload"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.file.File"][];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.upload": {
        parameters: {
            query?: {
                /** @description Get parameter `collectionId` from request url query. */
                collectionId?: components["schemas"]["takobox.types.uid.Uid"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upload a file. */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Response with json format data */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.file.File"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `file_id` from request url path. */
                file_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.file.FileWithCollections"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `file_id` from request url path. */
                file_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `file_id` from request url path. */
                file_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        /** @description Extract json format data from request. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["takobox.routes.files.RenameFilePayload"];
            };
        };
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.file.File"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `file_id` from request url path. */
                file_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.files.regenerate_thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Get parameter `file_id` from request url path. */
                file_id: components["schemas"]["takobox.types.uid.Uid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.me.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.user.User"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
    "takobox.routes.settings.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with json format data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.models.settings.Settings"];
                };
            };
            /** @description Error response */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
            /** @description Server error response */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["takobox.error.ErrorResponse"];
                };
            };
        };
    };
}
