name = "takobox"
version = "0.0.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 1.5.3 and < 2.0.0"
mist = ">= 4.0.6 and < 5.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
