name = "takobox"
version = "0.0.1"

[dependencies]
antigone = ">= 1.1.0 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
given = ">= 5.0.2 and < 6.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gwt = ">= 2.0.0 and < 3.0.0"
mist = ">= 4.0.6 and < 5.0.0"
pog = ">= 3.2.0 and < 4.0.0"
wisp = ">= 1.5.3 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 3.0.1 and < 4.0.0"
