name: Build and Push Docker Images (Dev)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            web:
              - "apps/web/**"
            server:
              - "apps/backend/**"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.web == 'true'
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/takobox-web:dev

      - name: Build and push server
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.server == 'true'
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/takobox-server:dev
